[tool.poetry]
name = "dynamic-dns-aws"
version = "0.1.0"
description = ""
authors = ["Max Pfeiffer <max@maxpfeiffer.ch>"]
readme = "README.md"
license = "MIT"

[tool.poetry.dependencies]
python = "3.12.*"
boto3 = "1.34.145"
requests = "2.32.3"

[tool.poetry.group.dev.dependencies]
pytest = "8.3.1"
pre-commit = "3.7.1"
ruff = "0.5.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
