[tool.poetry]
name = "dynamic-dns-aws"
version = "0.1.0"
description = ""
authors = ["Max Pfeiffer <max@maxpfeiffer.ch>"]
readme = "README.md"
license = "MIT"

[tool.poetry.dependencies]
python = "3.12.*"
boto3 = "1.34.145"
requests = "2.32.3"

[tool.poetry.group.dev.dependencies]
pre-commit = "3.7.1"
pytest = "8.3.1"
pytest-mock = "3.14.0"
pytest-dotenv = "0.5.2"
python-on-whales = "0.72.0"
responses = "0.25.3"
ruff = "0.5.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
